#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subs.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MIMS3")]
	public partial class MIMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerInvoice(CustomerInvoice instance);
    partial void UpdateCustomerInvoice(CustomerInvoice instance);
    partial void DeleteCustomerInvoice(CustomerInvoice instance);
    partial void InsertDormant(Dormant instance);
    partial void UpdateDormant(Dormant instance);
    partial void DeleteDormant(Dormant instance);
    partial void InsertInvoiceRaw(InvoiceRaw instance);
    partial void UpdateInvoiceRaw(InvoiceRaw instance);
    partial void DeleteInvoiceRaw(InvoiceRaw instance);
    partial void InsertPayerDerived(PayerDerived instance);
    partial void UpdatePayerDerived(PayerDerived instance);
    partial void DeletePayerDerived(PayerDerived instance);
    partial void InsertReceiverDerived(ReceiverDerived instance);
    partial void UpdateReceiverDerived(ReceiverDerived instance);
    partial void DeleteReceiverDerived(ReceiverDerived instance);
    partial void InsertWebProductAddition(WebProductAddition instance);
    partial void UpdateWebProductAddition(WebProductAddition instance);
    partial void DeleteWebProductAddition(WebProductAddition instance);
    partial void InsertInvoiceSpecification(InvoiceSpecification instance);
    partial void UpdateInvoiceSpecification(InvoiceSpecification instance);
    partial void DeleteInvoiceSpecification(InvoiceSpecification instance);
    #endregion
		
		public MIMSDataContext() : 
				base(global::Subs.Data.Properties.Settings.Default.MIMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MIMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MIMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SubscriptionOverlap> SubscriptionOverlaps
		{
			get
			{
				return this.GetTable<SubscriptionOverlap>();
			}
		}
		
		public System.Data.Linq.Table<CustomerInvoice> CustomerInvoices
		{
			get
			{
				return this.GetTable<CustomerInvoice>();
			}
		}
		
		public System.Data.Linq.Table<CustomerInvoices> CustomerInvoices1
		{
			get
			{
				return this.GetTable<CustomerInvoices>();
			}
		}
		
		public System.Data.Linq.Table<InvoicesAndPayments> InvoicesAndPayments
		{
			get
			{
				return this.GetTable<InvoicesAndPayments>();
			}
		}
		
		public System.Data.Linq.Table<SelectedSubscription> SelectedSubscriptions
		{
			get
			{
				return this.GetTable<SelectedSubscription>();
			}
		}
		
		public System.Data.Linq.Table<LiabilityRecord> LiabilityRecords
		{
			get
			{
				return this.GetTable<LiabilityRecord>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceIds> InvoiceIds
		{
			get
			{
				return this.GetTable<InvoiceIds>();
			}
		}
		
		public System.Data.Linq.Table<DebitOrderProposal> DebitOrderProposals
		{
			get
			{
				return this.GetTable<DebitOrderProposal>();
			}
		}
		
		public System.Data.Linq.Table<Dormant> Dormants
		{
			get
			{
				return this.GetTable<Dormant>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceRaw> InvoiceRaws
		{
			get
			{
				return this.GetTable<InvoiceRaw>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		public System.Data.Linq.Table<DOCashBook> DOCashBooks
		{
			get
			{
				return this.GetTable<DOCashBook>();
			}
		}
		
		public System.Data.Linq.Table<SBCashBook> SBCashBooks
		{
			get
			{
				return this.GetTable<SBCashBook>();
			}
		}
		
		public System.Data.Linq.Table<CreditNote> CreditNotes
		{
			get
			{
				return this.GetTable<CreditNote>();
			}
		}
		
		public System.Data.Linq.Table<Subscription> Subscriptions
		{
			get
			{
				return this.GetTable<Subscription>();
			}
		}
		
		public System.Data.Linq.Table<PayerDerived> PayerDeriveds
		{
			get
			{
				return this.GetTable<PayerDerived>();
			}
		}
		
		public System.Data.Linq.Table<ReceiverDerived> ReceiverDeriveds
		{
			get
			{
				return this.GetTable<ReceiverDerived>();
			}
		}
		
		public System.Data.Linq.Table<WebProductAddition> WebProductAdditions
		{
			get
			{
				return this.GetTable<WebProductAddition>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceSpecification> InvoiceSpecifications
		{
			get
			{
				return this.GetTable<InvoiceSpecification>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.SubscriptionOverlapPrime]")]
		public ISingleResult<MIMS_SubscriptionData_SubscriptionOverlapPrimeResult> MIMS_SubscriptionData_SubscriptionOverlapPrime()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MIMS_SubscriptionData_SubscriptionOverlapPrimeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.SubscriptionOverlap]")]
		public ISingleResult<SubscriptionOverlap> MIMS_SubscriptionData_SubscriptionOverlap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receiver", DbType="Int")] System.Nullable<int> receiver, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartIssue", DbType="Int")] System.Nullable<int> startIssue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastIssue", DbType="Int")] System.Nullable<int> lastIssue)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), receiver, startIssue, lastIssue);
			return ((ISingleResult<SubscriptionOverlap>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionBiz.ProposeLastIssue]")]
		public ISingleResult<MIMS_SubscriptionBiz_ProposeLastIssueResult> MIMS_SubscriptionBiz_ProposeLastIssue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartSequence", DbType="Int")] System.Nullable<int> startSequence)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, startSequence);
			return ((ISingleResult<MIMS_SubscriptionBiz_ProposeLastIssueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.LedgerDoc.CreditNoteBatch.Load]")]
		public ISingleResult<MIMS_LedgerDoc_CreditNoteBatch_LoadResult> MIMS_LedgerDoc_CreditNoteBatch_Load()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MIMS_LedgerDoc_CreditNoteBatch_LoadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionDoc.SubscriptionIssue.Reverseables]")]
		public ISingleResult<MIMS_SubscriptionDoc_SubscriptionIssue_ReverseablesResult> MIMS_SubscriptionDoc_SubscriptionIssue_Reverseables([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), payerId);
			return ((ISingleResult<MIMS_SubscriptionDoc_SubscriptionIssue_ReverseablesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.CustomerData.GetInvoicesFromPayment]")]
		public ISingleResult<InvoiceIds> MIMS_CustomerData_GetInvoicesFromPayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentTransactionId", DbType="Int")] System.Nullable<int> paymentTransactionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentTransactionId);
			return ((ISingleResult<InvoiceIds>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoicePayment.DeleteByPaymentTransactionId]")]
		public int MIMS_InvoicePayment_DeleteByPaymentTransactionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentTransactionId", DbType="Int")] System.Nullable<int> paymentTransactionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentTransactionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoicePayment.Insert]")]
		public int MIMS_InvoicePayment_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceId", DbType="Int")] System.Nullable<int> invoiceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentTransactionId", DbType="Int")] System.Nullable<int> paymentTransactionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(16,6)")] System.Nullable<decimal> amount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoiceId, paymentTransactionId, amount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.Deliveries]")]
		public ISingleResult<LiabilityRecord> MIMS_DataContext_Deliveries([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), payerId);
			return ((ISingleResult<LiabilityRecord>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.InvoicesAndPayments]")]
		public ISingleResult<InvoicesAndPayments> MIMS_DataContext_InvoicesAndPayments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), payerId);
			return ((ISingleResult<InvoicesAndPayments>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.SubscriptionsByInvoice]")]
		public ISingleResult<SelectedSubscription> MIMS_DataContext_SubscriptionsByInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceId", DbType="Int")] System.Nullable<int> invoiceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoiceId);
			return ((ISingleResult<SelectedSubscription>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.SubscriptionsByDate]")]
		public ISingleResult<SelectedSubscription> MIMS_DataContext_SubscriptionsByDate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateFrom", DbType="DateTime")] System.Nullable<System.DateTime> dateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateFrom, payerId);
			return ((ISingleResult<SelectedSubscription>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.DestroySubscription]")]
		public int MIMS_SubscriptionData_DestroySubscription([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionId", DbType="Int")] System.Nullable<int> subscriptionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subscriptionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.NextIssue]")]
		public ISingleResult<MIMS_SubscriptionData_NextIssueResult> MIMS_SubscriptionData_NextIssue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssueId", DbType="Int")] System.Nullable<int> issueId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), issueId);
			return ((ISingleResult<MIMS_SubscriptionData_NextIssueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DeliveryDataStatic.Dormants]")]
		public ISingleResult<Dormant> MIMS_DeliveryDataStatic_Dormants()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Dormant>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionBiz.Authorize]")]
		public ISingleResult<MIMS_SubscriptionBiz_AuthorizeResult> MIMS_SubscriptionBiz_Authorize([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverId", DbType="Int")] System.Nullable<int> receiverId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, receiverId);
			return ((ISingleResult<MIMS_SubscriptionBiz_AuthorizeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoicePayment.DeleteByInvoiceId]")]
		public int MIMS_InvoicePayment_DeleteByInvoiceId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceId", DbType="Int")] System.Nullable<int> invoiceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoiceId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoiceData.Generate]")]
		public ISingleResult<InvoiceRaw> MIMS_InvoiceData_Generate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromTransactionId", DbType="Int")] System.Nullable<int> fromTransactionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fromTransactionId);
			return ((ISingleResult<InvoiceRaw>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionBiz.SetInitialValues]")]
		public ISingleResult<MIMS_SubscriptionBiz_SetInitialValuesResult> MIMS_SubscriptionBiz_SetInitialValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverId", DbType="Int")] System.Nullable<int> receiverId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateFrom", DbType="DateTime")] System.Nullable<System.DateTime> dateFrom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), payerId, receiverId, productId, dateFrom);
			return ((ISingleResult<MIMS_SubscriptionBiz_SetInitialValuesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoiceControl.LoadInvoice]")]
		public ISingleResult<Invoice> MIMS_InvoiceControl_LoadInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceId", DbType="Int")] System.Nullable<int> invoiceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoiceId);
			return ((ISingleResult<Invoice>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.PaymentData.DuplicateSBRow]")]
		public ISingleResult<MIMS_PaymentData_DuplicateSBRowResult> MIMS_PaymentData_DuplicateSBRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionDate", DbType="DateTime")] System.Nullable<System.DateTime> transactionDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(18,6)")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(40)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatementNo", DbType="Int")] System.Nullable<int> statementNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllocationNo", DbType="Decimal(4,1)")] System.Nullable<decimal> allocationNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), transactionDate, amount, reference, statementNo, allocationNo);
			return ((ISingleResult<MIMS_PaymentData_DuplicateSBRowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.LedgerData.ReversePaymentCheck]")]
		public ISingleResult<MIMS_LedgerData_ReversePaymentCheckResult> MIMS_LedgerData_ReversePaymentCheck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentTransactionId", DbType="Int")] System.Nullable<int> paymentTransactionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paymentTransactionId);
			return ((ISingleResult<MIMS_LedgerData_ReversePaymentCheckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.IssueBiz.GetIssueId]")]
		public ISingleResult<MIMS_IssueBiz_GetIssueIdResult> MIMS_IssueBiz_GetIssueId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SequenceNumber", DbType="Int")] System.Nullable<int> sequenceNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, sequenceNumber);
			return ((ISingleResult<MIMS_IssueBiz_GetIssueIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.IssueBiz.GetSequenceNumber]")]
		public ISingleResult<MIMS_IssueBiz_GetSequenceNumberResult> MIMS_IssueBiz_GetSequenceNumber([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssueId", DbType="Int")] System.Nullable<int> issueId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), issueId);
			return ((ISingleResult<MIMS_IssueBiz_GetSequenceNumberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.CreditNote]")]
		public ISingleResult<CreditNote> MIMS_SubscriptionData_CreditNote([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionId", DbType="Int")] System.Nullable<int> subscriptionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subscriptionId);
			return ((ISingleResult<CreditNote>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.DebitOrder.Proposal]")]
		public ISingleResult<DebitOrderProposal> MIMS_DataContext_DebitOrder_Proposal([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeliveryMonthFirstDay", DbType="DateTime")] System.Nullable<System.DateTime> deliveryMonthFirstDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deliveryMonthFirstDay);
			return ((ISingleResult<DebitOrderProposal>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.PaymentData.SBCashbook]")]
		public ISingleResult<SBCashBook> MIMS_PaymentData_SBCashbook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Month", DbType="DateTime")] System.Nullable<System.DateTime> month)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), month);
			return ((ISingleResult<SBCashBook>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.PaymentData.DOCashbook]")]
		public ISingleResult<DOCashBook> MIMS_PaymentData_DOCashbook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Month", DbType="DateTime")] System.Nullable<System.DateTime> month)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), month);
			return ((ISingleResult<DOCashBook>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.FillById]")]
		public ISingleResult<Subscription> MIMS_SubscriptionData_FillById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="NVarChar(30)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id1", DbType="Int")] System.Nullable<int> id1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id2", DbType="Int")] System.Nullable<int> id2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type, id1, id2);
			return ((ISingleResult<Subscription>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.InvoiceData.ActiveSubscriptionsBefore]")]
		public ISingleResult<MIMS_InvoiceData_ActiveSubscriptionsBeforeResult> MIMS_InvoiceData_ActiveSubscriptionsBefore([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateFrom", DbType="DateTime")] System.Nullable<System.DateTime> dateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayerId", DbType="Int")] System.Nullable<int> payerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateFrom, payerId);
			return ((ISingleResult<MIMS_InvoiceData_ActiveSubscriptionsBeforeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DeliveryDataStatic.DeliverableElectronic]")]
		public ISingleResult<MIMS_DeliveryDataStatic_DeliverableElectronicResult> MIMS_DeliveryDataStatic_DeliverableElectronic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverId", DbType="Int")] System.Nullable<int> receiverId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), receiverId);
			return ((ISingleResult<MIMS_DeliveryDataStatic_DeliverableElectronicResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.ProducData.WebAddition]")]
		public ISingleResult<WebProductAddition> MIMS_ProducData_WebAddition()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<WebProductAddition>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.LedgerData.LoadInvoiceBatch]")]
		public ISingleResult<InvoiceSpecification> MIMS_LedgerData_LoadInvoiceBatch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="NVarChar(20)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type, id);
			return ((ISingleResult<InvoiceSpecification>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.DerivedPayer.FillById]")]
		public ISingleResult<PayerDerived> MIMS_SubscriptionData_DerivedPayer_FillById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="Int")] System.Nullable<int> customerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerId);
			return ((ISingleResult<PayerDerived>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.SubscriptionData.DerivedReceiver.FillById]")]
		public ISingleResult<ReceiverDerived> MIMS_SubscriptionData_DerivedReceiver_FillById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="Int")] System.Nullable<int> customerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerId);
			return ((ISingleResult<ReceiverDerived>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.Customer.Select]")]
		public ISingleResult<Customer> MIMS_DataContext_Customer_Select([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="NVarChar(20)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IntegerId", DbType="Int")] System.Nullable<int> integerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StringId", DbType="NVarChar(80)")] string stringId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type, integerId, stringId);
			return ((ISingleResult<Customer>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DeliveryAddressDoc.DeliveryAddress.NonStandard]")]
		public ISingleResult<MIMS_DeliveryAddressDoc_DeliveryAddress_NonStandardResult> MIMS_DeliveryAddressDoc_DeliveryAddress_NonStandard()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MIMS_DeliveryAddressDoc_DeliveryAddress_NonStandardResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SubscriptionOverlap
	{
		
		private int _SubscriptionId;
		
		private int _OverlapId;
		
		public SubscriptionOverlap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverlapId")]
		public int OverlapId
		{
			get
			{
				return this._OverlapId;
			}
			set
			{
				if ((this._OverlapId != value))
				{
					this._OverlapId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CustomerInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VatInvoiceNumber;
		
		private decimal _InvoiceValue;
		
		private decimal _Outstanding;
		
		private System.DateTime _InvoiceDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceIdChanging(int value);
    partial void OnInvoiceIdChanged();
    partial void OnInvoiceValueChanging(decimal value);
    partial void OnInvoiceValueChanged();
    partial void OnOutstandingChanging(decimal value);
    partial void OnOutstandingChanged();
    partial void OnInvoiceDateChanging(System.DateTime value);
    partial void OnInvoiceDateChanged();
    #endregion
		
		public CustomerInvoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatInvoiceNumber", IsPrimaryKey=true)]
		public int InvoiceId
		{
			get
			{
				return this._VatInvoiceNumber;
			}
			set
			{
				if ((this._VatInvoiceNumber != value))
				{
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._VatInvoiceNumber = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue")]
		public decimal InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this.OnInvoiceValueChanging(value);
					this.SendPropertyChanging();
					this._InvoiceValue = value;
					this.SendPropertyChanged("InvoiceValue");
					this.OnInvoiceValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Outstanding")]
		public decimal Outstanding
		{
			get
			{
				return this._Outstanding;
			}
			set
			{
				if ((this._Outstanding != value))
				{
					this.OnOutstandingChanging(value);
					this.SendPropertyChanging();
					this._Outstanding = value;
					this.SendPropertyChanged("Outstanding");
					this.OnOutstandingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate")]
		public System.DateTime InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CustomerInvoices
	{
		
		private List<CustomerInvoice> _Invoices;
		
		public CustomerInvoices()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoices", CanBeNull=false)]
		public List<CustomerInvoice> Invoices
		{
			get
			{
				return this._Invoices;
			}
			set
			{
				if ((this._Invoices != value))
				{
					this._Invoices = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class InvoicesAndPayments
	{
		
		private string _Operation;
		
		private System.DateTime _Date;
		
		private int _Reference1;
		
		private string _Reference2;
		
		private decimal _Value;
		
		private decimal _InvoiceBalance;
		
		private decimal _StatementBalance;
		
		private int _TransactionId;
		
		private bool _FirstRow;
		
		private bool _LastRow;
		
		private int _OperationId;
		
		public InvoicesAndPayments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", CanBeNull=false)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference1")]
		public int InvoiceId
		{
			get
			{
				return this._Reference1;
			}
			set
			{
				if ((this._Reference1 != value))
				{
					this._Reference1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference2", CanBeNull=false)]
		public string Reference2
		{
			get
			{
				return this._Reference2;
			}
			set
			{
				if ((this._Reference2 != value))
				{
					this._Reference2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value")]
		public decimal Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceBalance")]
		public decimal InvoiceBalance
		{
			get
			{
				return this._InvoiceBalance;
			}
			set
			{
				if ((this._InvoiceBalance != value))
				{
					this._InvoiceBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementBalance")]
		public decimal StatementBalance
		{
			get
			{
				return this._StatementBalance;
			}
			set
			{
				if ((this._StatementBalance != value))
				{
					this._StatementBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId")]
		public int TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this._TransactionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstRow", DbType="bit")]
		public bool FirstRow
		{
			get
			{
				return this._FirstRow;
			}
			set
			{
				if ((this._FirstRow != value))
				{
					this._FirstRow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastRow")]
		public bool LastRow
		{
			get
			{
				return this._LastRow;
			}
			set
			{
				if ((this._LastRow != value))
				{
					this._LastRow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationId")]
		public int OperationId
		{
			get
			{
				return this._OperationId;
			}
			set
			{
				if ((this._OperationId != value))
				{
					this._OperationId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SelectedSubscription
	{
		
		private int _SubscriptionId;
		
		private string _Status;
		
		private string _ProductName;
		
		private decimal _UnitPrice;
		
		private int _NumberOfIssues;
		
		private int _UnitsPerIssue;
		
		private decimal _Value;
		
		public SelectedSubscription()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfIssues")]
		public int NumberOfIssues
		{
			get
			{
				return this._NumberOfIssues;
			}
			set
			{
				if ((this._NumberOfIssues != value))
				{
					this._NumberOfIssues = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsPerIssue")]
		public int UnitsPerIssue
		{
			get
			{
				return this._UnitsPerIssue;
			}
			set
			{
				if ((this._UnitsPerIssue != value))
				{
					this._UnitsPerIssue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value")]
		public decimal Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class LiabilityRecord
	{
		
		private int _TransactionId;
		
		private System.DateTime _Date;
		
		private string _Operation;
		
		private int _InvoiceId;
		
		private int _SubscriptionId;
		
		private decimal _Value;
		
		private System.Nullable<decimal> _Balance;
		
		public LiabilityRecord()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId")]
		public int TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this._TransactionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", CanBeNull=false)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId")]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this._InvoiceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value")]
		public decimal Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class InvoiceIds
	{
		
		private int _InvoiceId;
		
		public InvoiceIds()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId")]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this._InvoiceId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class DebitOrderProposal
	{
		
		private string _EmailAddress;
		
		private string _AccountNo;
		
		private string _AccountHolder;
		
		private string _BankCode;
		
		private string _Bank;
		
		private int _CustomerId;
		
		private string _ProductName;
		
		private int _SubscriptionId;
		
		private int _IssueId;
		
		private string _IssueDescription;
		
		private string _Classification;
		
		private decimal _Subtract;
		
		public DebitOrderProposal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", CanBeNull=false)]
		public string AccountNo
		{
			get
			{
				return this._AccountNo;
			}
			set
			{
				if ((this._AccountNo != value))
				{
					this._AccountNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountHolder", CanBeNull=false)]
		public string AccountHolder
		{
			get
			{
				return this._AccountHolder;
			}
			set
			{
				if ((this._AccountHolder != value))
				{
					this._AccountHolder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCode", CanBeNull=false)]
		public string BankCode
		{
			get
			{
				return this._BankCode;
			}
			set
			{
				if ((this._BankCode != value))
				{
					this._BankCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", CanBeNull=false)]
		public string Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this._Bank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId")]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this._CustomerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueId")]
		public int IssueId
		{
			get
			{
				return this._IssueId;
			}
			set
			{
				if ((this._IssueId != value))
				{
					this._IssueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueDescription", CanBeNull=false)]
		public string IssueDescription
		{
			get
			{
				return this._IssueDescription;
			}
			set
			{
				if ((this._IssueDescription != value))
				{
					this._IssueDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", CanBeNull=false)]
		public string Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					this._Classification = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtract")]
		public decimal Subtract
		{
			get
			{
				return this._Subtract;
			}
			set
			{
				if ((this._Subtract != value))
				{
					this._Subtract = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Dormant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubscriptionId;
		
		private System.DateTime _LastDeliveryDate;
		
		private string _ProductName;
		
		private int _Payer;
		
		private decimal _Liability;
		
		private int _LastSequenceByProduct;
		
		private int _LastSequencebySubscription;
		
		private int _LagByIssues;
		
		private int _DeliverableIssueId;
		
		private string _DeliverableIssueName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubscriptionIdChanging(int value);
    partial void OnSubscriptionIdChanged();
    partial void OnLastDeliveryDateChanging(System.DateTime value);
    partial void OnLastDeliveryDateChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnPayerChanging(int value);
    partial void OnPayerChanged();
    partial void OnLiabilityChanging(decimal value);
    partial void OnLiabilityChanged();
    partial void OnLastSequenceByProductChanging(int value);
    partial void OnLastSequenceByProductChanged();
    partial void OnLastSequencebySubscriptionChanging(int value);
    partial void OnLastSequencebySubscriptionChanged();
    partial void OnLagByIssuesChanging(int value);
    partial void OnLagByIssuesChanged();
    partial void OnDeliverableIssueIdChanging(int value);
    partial void OnDeliverableIssueIdChanged();
    partial void OnDeliverableIssueNameChanging(string value);
    partial void OnDeliverableIssueNameChanged();
    #endregion
		
		public Dormant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", IsPrimaryKey=true)]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDeliveryDate")]
		public System.DateTime LastDeliveryDate
		{
			get
			{
				return this._LastDeliveryDate;
			}
			set
			{
				if ((this._LastDeliveryDate != value))
				{
					this.OnLastDeliveryDateChanging(value);
					this.SendPropertyChanging();
					this._LastDeliveryDate = value;
					this.SendPropertyChanged("LastDeliveryDate");
					this.OnLastDeliveryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payer")]
		public int Payer
		{
			get
			{
				return this._Payer;
			}
			set
			{
				if ((this._Payer != value))
				{
					this.OnPayerChanging(value);
					this.SendPropertyChanging();
					this._Payer = value;
					this.SendPropertyChanged("Payer");
					this.OnPayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liability")]
		public decimal Liability
		{
			get
			{
				return this._Liability;
			}
			set
			{
				if ((this._Liability != value))
				{
					this.OnLiabilityChanging(value);
					this.SendPropertyChanging();
					this._Liability = value;
					this.SendPropertyChanged("Liability");
					this.OnLiabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSequenceByProduct")]
		public int LastSequenceByProduct
		{
			get
			{
				return this._LastSequenceByProduct;
			}
			set
			{
				if ((this._LastSequenceByProduct != value))
				{
					this.OnLastSequenceByProductChanging(value);
					this.SendPropertyChanging();
					this._LastSequenceByProduct = value;
					this.SendPropertyChanged("LastSequenceByProduct");
					this.OnLastSequenceByProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSequencebySubscription")]
		public int LastSequencebySubscription
		{
			get
			{
				return this._LastSequencebySubscription;
			}
			set
			{
				if ((this._LastSequencebySubscription != value))
				{
					this.OnLastSequencebySubscriptionChanging(value);
					this.SendPropertyChanging();
					this._LastSequencebySubscription = value;
					this.SendPropertyChanged("LastSequencebySubscription");
					this.OnLastSequencebySubscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LagByIssues")]
		public int LagByIssues
		{
			get
			{
				return this._LagByIssues;
			}
			set
			{
				if ((this._LagByIssues != value))
				{
					this.OnLagByIssuesChanging(value);
					this.SendPropertyChanging();
					this._LagByIssues = value;
					this.SendPropertyChanged("LagByIssues");
					this.OnLagByIssuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliverableIssueId")]
		public int DeliverableIssueId
		{
			get
			{
				return this._DeliverableIssueId;
			}
			set
			{
				if ((this._DeliverableIssueId != value))
				{
					this.OnDeliverableIssueIdChanging(value);
					this.SendPropertyChanging();
					this._DeliverableIssueId = value;
					this.SendPropertyChanged("DeliverableIssueId");
					this.OnDeliverableIssueIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliverableIssueName", CanBeNull=false)]
		public string DeliverableIssueName
		{
			get
			{
				return this._DeliverableIssueName;
			}
			set
			{
				if ((this._DeliverableIssueName != value))
				{
					this.OnDeliverableIssueNameChanging(value);
					this.SendPropertyChanging();
					this._DeliverableIssueName = value;
					this.SendPropertyChanged("DeliverableIssueName");
					this.OnDeliverableIssueNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class InvoiceRaw : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PayerId;
		
		private string _EMailAddress;
		
		private int _SubscriptionId;
		
		private int _TransactionId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayerIdChanging(int value);
    partial void OnPayerIdChanged();
    partial void OnEMailAddressChanging(string value);
    partial void OnEMailAddressChanged();
    partial void OnSubscriptionIdChanging(int value);
    partial void OnSubscriptionIdChanged();
    partial void OnTransactionIdChanging(int value);
    partial void OnTransactionIdChanged();
    #endregion
		
		public InvoiceRaw()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerId")]
		public int PayerId
		{
			get
			{
				return this._PayerId;
			}
			set
			{
				if ((this._PayerId != value))
				{
					this.OnPayerIdChanging(value);
					this.SendPropertyChanging();
					this._PayerId = value;
					this.SendPropertyChanged("PayerId");
					this.OnPayerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMailAddress", CanBeNull=false)]
		public string EMailAddress
		{
			get
			{
				return this._EMailAddress;
			}
			set
			{
				if ((this._EMailAddress != value))
				{
					this.OnEMailAddressChanging(value);
					this.SendPropertyChanging();
					this._EMailAddress = value;
					this.SendPropertyChanged("EMailAddress");
					this.OnEMailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId", IsPrimaryKey=true)]
		public int TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this.OnTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._TransactionId = value;
					this.SendPropertyChanged("TransactionId");
					this.OnTransactionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Customer
	{
		
		private int _CustomerId;
		
		public Customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId")]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this._CustomerId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Invoice
	{
		
		private int _InvoiceId;
		
		private int _PayerId;
		
		private int _SubscriptionId;
		
		private System.DateTime _DateFrom;
		
		public Invoice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId")]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this._InvoiceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerId")]
		public int PayerId
		{
			get
			{
				return this._PayerId;
			}
			set
			{
				if ((this._PayerId != value))
				{
					this._PayerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFrom")]
		public System.DateTime DateFrom
		{
			get
			{
				return this._DateFrom;
			}
			set
			{
				if ((this._DateFrom != value))
				{
					this._DateFrom = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class DOCashBook
	{
		
		private string _ProductName;
		
		private decimal _Amount;
		
		private string _Nationality;
		
		public DOCashBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", CanBeNull=false)]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this._Nationality = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SBCashBook
	{
		
		private int _StatementNo;
		
		private System.DateTime _StatementDate;
		
		private string _BankTransactionType;
		
		private decimal _Amount;
		
		private string _BankPaymentMethod;
		
		private string _Reference;
		
		private string _PaymentType;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _Payment;
		
		private string _Nationality;
		
		private decimal _AllocationNo;
		
		public SBCashBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementNo")]
		public int StatementNo
		{
			get
			{
				return this._StatementNo;
			}
			set
			{
				if ((this._StatementNo != value))
				{
					this._StatementNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementDate")]
		public System.DateTime StatementDate
		{
			get
			{
				return this._StatementDate;
			}
			set
			{
				if ((this._StatementDate != value))
				{
					this._StatementDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankTransactionType", CanBeNull=false)]
		public string BankTransactionType
		{
			get
			{
				return this._BankTransactionType;
			}
			set
			{
				if ((this._BankTransactionType != value))
				{
					this._BankTransactionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankPaymentMethod", CanBeNull=false)]
		public string BankPaymentMethod
		{
			get
			{
				return this._BankPaymentMethod;
			}
			set
			{
				if ((this._BankPaymentMethod != value))
				{
					this._BankPaymentMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference", CanBeNull=false)]
		public string Reference
		{
			get
			{
				return this._Reference;
			}
			set
			{
				if ((this._Reference != value))
				{
					this._Reference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", CanBeNull=false)]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this._PaymentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment")]
		public System.Nullable<decimal> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this._Payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", CanBeNull=false)]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this._Nationality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllocationNo")]
		public decimal AllocationNo
		{
			get
			{
				return this._AllocationNo;
			}
			set
			{
				if ((this._AllocationNo != value))
				{
					this._AllocationNo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CreditNote
	{
		
		private string _CreditNoteName;
		
		private decimal _CreditNoteValue;
		
		public CreditNote()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditNoteName", CanBeNull=false)]
		public string CreditNoteName
		{
			get
			{
				return this._CreditNoteName;
			}
			set
			{
				if ((this._CreditNoteName != value))
				{
					this._CreditNoteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditNoteValue")]
		public decimal CreditNoteValue
		{
			get
			{
				return this._CreditNoteValue;
			}
			set
			{
				if ((this._CreditNoteValue != value))
				{
					this._CreditNoteValue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Subscription
	{
		
		private int _SubscriptionId;
		
		public Subscription()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class PayerDerived : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubscriptionId;
		
		private string _PayerCompany;
		
		private int _PayerCountryId;
		
		private string _PayerSurname;
		
		private string _PayerPhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayerIdChanging(int value);
    partial void OnPayerIdChanged();
    partial void OnPayerCompanyChanging(string value);
    partial void OnPayerCompanyChanged();
    partial void OnPayerCountryIdChanging(int value);
    partial void OnPayerCountryIdChanged();
    partial void OnPayerSurnameChanging(string value);
    partial void OnPayerSurnameChanged();
    partial void OnPayerPhoneNumberChanging(string value);
    partial void OnPayerPhoneNumberChanged();
    #endregion
		
		public PayerDerived()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", IsPrimaryKey=true)]
		public int PayerId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnPayerIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("PayerId");
					this.OnPayerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerCompany", CanBeNull=false)]
		public string PayerCompany
		{
			get
			{
				return this._PayerCompany;
			}
			set
			{
				if ((this._PayerCompany != value))
				{
					this.OnPayerCompanyChanging(value);
					this.SendPropertyChanging();
					this._PayerCompany = value;
					this.SendPropertyChanged("PayerCompany");
					this.OnPayerCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerCountryId")]
		public int PayerCountryId
		{
			get
			{
				return this._PayerCountryId;
			}
			set
			{
				if ((this._PayerCountryId != value))
				{
					this.OnPayerCountryIdChanging(value);
					this.SendPropertyChanging();
					this._PayerCountryId = value;
					this.SendPropertyChanged("PayerCountryId");
					this.OnPayerCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerSurname", CanBeNull=false)]
		public string PayerSurname
		{
			get
			{
				return this._PayerSurname;
			}
			set
			{
				if ((this._PayerSurname != value))
				{
					this.OnPayerSurnameChanging(value);
					this.SendPropertyChanging();
					this._PayerSurname = value;
					this.SendPropertyChanged("PayerSurname");
					this.OnPayerSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerPhoneNumber", CanBeNull=false)]
		public string PayerPhoneNumber
		{
			get
			{
				return this._PayerPhoneNumber;
			}
			set
			{
				if ((this._PayerPhoneNumber != value))
				{
					this.OnPayerPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PayerPhoneNumber = value;
					this.SendPropertyChanged("PayerPhoneNumber");
					this.OnPayerPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class ReceiverDerived : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubscriptionId;
		
		private string _ReceiverSurname;
		
		private string _ReceiverCompany;
		
		private string _ReceiverDepartment;
		
		private int _ReceiverCountryId;
		
		private string _ReceiverEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReceiverIdChanging(int value);
    partial void OnReceiverIdChanged();
    partial void OnReceiverSurnameChanging(string value);
    partial void OnReceiverSurnameChanged();
    partial void OnReceiverCompanyChanging(string value);
    partial void OnReceiverCompanyChanged();
    partial void OnReceiverDepartmentChanging(string value);
    partial void OnReceiverDepartmentChanged();
    partial void OnReceiverCountryIdChanging(int value);
    partial void OnReceiverCountryIdChanged();
    partial void OnReceiverEmailChanging(string value);
    partial void OnReceiverEmailChanged();
    #endregion
		
		public ReceiverDerived()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", IsPrimaryKey=true)]
		public int ReceiverId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnReceiverIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("ReceiverId");
					this.OnReceiverIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverSurname", CanBeNull=false)]
		public string ReceiverSurname
		{
			get
			{
				return this._ReceiverSurname;
			}
			set
			{
				if ((this._ReceiverSurname != value))
				{
					this.OnReceiverSurnameChanging(value);
					this.SendPropertyChanging();
					this._ReceiverSurname = value;
					this.SendPropertyChanged("ReceiverSurname");
					this.OnReceiverSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverCompany", CanBeNull=false)]
		public string ReceiverCompany
		{
			get
			{
				return this._ReceiverCompany;
			}
			set
			{
				if ((this._ReceiverCompany != value))
				{
					this.OnReceiverCompanyChanging(value);
					this.SendPropertyChanging();
					this._ReceiverCompany = value;
					this.SendPropertyChanged("ReceiverCompany");
					this.OnReceiverCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverDepartment", CanBeNull=false)]
		public string ReceiverDepartment
		{
			get
			{
				return this._ReceiverDepartment;
			}
			set
			{
				if ((this._ReceiverDepartment != value))
				{
					this.OnReceiverDepartmentChanging(value);
					this.SendPropertyChanging();
					this._ReceiverDepartment = value;
					this.SendPropertyChanged("ReceiverDepartment");
					this.OnReceiverDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverCountryId")]
		public int ReceiverCountryId
		{
			get
			{
				return this._ReceiverCountryId;
			}
			set
			{
				if ((this._ReceiverCountryId != value))
				{
					this.OnReceiverCountryIdChanging(value);
					this.SendPropertyChanging();
					this._ReceiverCountryId = value;
					this.SendPropertyChanged("ReceiverCountryId");
					this.OnReceiverCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverEmail", CanBeNull=false)]
		public string ReceiverEmail
		{
			get
			{
				return this._ReceiverEmail;
			}
			set
			{
				if ((this._ReceiverEmail != value))
				{
					this.OnReceiverEmailChanging(value);
					this.SendPropertyChanging();
					this._ReceiverEmail = value;
					this.SendPropertyChanged("ReceiverEmail");
					this.OnReceiverEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class WebProductAddition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductId;
		
		private bool _CPDEnabled;
		
		private decimal _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnCPDEnabledChanging(bool value);
    partial void OnCPDEnabledChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    #endregion
		
		public WebProductAddition()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", IsPrimaryKey=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPDEnabled")]
		public bool CPDEnabled
		{
			get
			{
				return this._CPDEnabled;
			}
			set
			{
				if ((this._CPDEnabled != value))
				{
					this.OnCPDEnabledChanging(value);
					this.SendPropertyChanging();
					this._CPDEnabled = value;
					this.SendPropertyChanged("CPDEnabled");
					this.OnCPDEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class InvoiceSpecification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubscriptionId;
		
		private int _PayerId;
		
		private string _EmailAddress;
		
		private int _TransactionId;
		
		private int _InvoiceId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubscriptionIdChanging(int value);
    partial void OnSubscriptionIdChanged();
    partial void OnPayerIdChanging(int value);
    partial void OnPayerIdChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnTransactionIdChanging(int value);
    partial void OnTransactionIdChanged();
    partial void OnInvoiceIdChanging(int value);
    partial void OnInvoiceIdChanged();
    #endregion
		
		public InvoiceSpecification()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", IsPrimaryKey=true)]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_PayerId")]
		public int PayerId
		{
			get
			{
				return this._PayerId;
			}
			set
			{
				if ((this._PayerId != value))
				{
					this.OnPayerIdChanging(value);
					this.SendPropertyChanging();
					this._PayerId = value;
					this.SendPropertyChanged("PayerId");
					this.OnPayerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId")]
		public int TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this.OnTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._TransactionId = value;
					this.SendPropertyChanged("TransactionId");
					this.OnTransactionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId")]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceId = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class MIMS_SubscriptionData_SubscriptionOverlapPrimeResult
	{
		
		private System.Nullable<int> _OverlapId;
		
		public MIMS_SubscriptionData_SubscriptionOverlapPrimeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverlapId", DbType="Int")]
		public System.Nullable<int> OverlapId
		{
			get
			{
				return this._OverlapId;
			}
			set
			{
				if ((this._OverlapId != value))
				{
					this._OverlapId = value;
				}
			}
		}
	}
	
	public partial class MIMS_SubscriptionBiz_ProposeLastIssueResult
	{
		
		private int _LastIssue;
		
		private int _LastSequence;
		
		public MIMS_SubscriptionBiz_ProposeLastIssueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIssue", DbType="Int NOT NULL")]
		public int LastIssue
		{
			get
			{
				return this._LastIssue;
			}
			set
			{
				if ((this._LastIssue != value))
				{
					this._LastIssue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSequence", DbType="Int NOT NULL")]
		public int LastSequence
		{
			get
			{
				return this._LastSequence;
			}
			set
			{
				if ((this._LastSequence != value))
				{
					this._LastSequence = value;
				}
			}
		}
	}
	
	public partial class MIMS_LedgerDoc_CreditNoteBatch_LoadResult
	{
		
		private int _PayerId;
		
		private System.Nullable<int> _SubscriptionId;
		
		private decimal _UnitPrice;
		
		private System.Nullable<int> _UnitsLess;
		
		private string _InvoiceNumber;
		
		private string _CreditnoteNumber;
		
		private string _Explanation;
		
		private string _EmailAddress;
		
		private string _InvoiceEmail;
		
		public MIMS_LedgerDoc_CreditNoteBatch_LoadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerId", DbType="Int NOT NULL")]
		public int PayerId
		{
			get
			{
				return this._PayerId;
			}
			set
			{
				if ((this._PayerId != value))
				{
					this._PayerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="Int")]
		public System.Nullable<int> SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Decimal(12,6) NOT NULL")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsLess", DbType="Int")]
		public System.Nullable<int> UnitsLess
		{
			get
			{
				return this._UnitsLess;
			}
			set
			{
				if ((this._UnitsLess != value))
				{
					this._UnitsLess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(40)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditnoteNumber", DbType="NVarChar(40)")]
		public string CreditnoteNumber
		{
			get
			{
				return this._CreditnoteNumber;
			}
			set
			{
				if ((this._CreditnoteNumber != value))
				{
					this._CreditnoteNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Explanation", DbType="NVarChar(200)")]
		public string Explanation
		{
			get
			{
				return this._Explanation;
			}
			set
			{
				if ((this._Explanation != value))
				{
					this._Explanation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(80)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceEmail", DbType="NVarChar(80)")]
		public string InvoiceEmail
		{
			get
			{
				return this._InvoiceEmail;
			}
			set
			{
				if ((this._InvoiceEmail != value))
				{
					this._InvoiceEmail = value;
				}
			}
		}
	}
	
	public partial class MIMS_SubscriptionDoc_SubscriptionIssue_ReverseablesResult
	{
		
		private int _IssueId;
		
		private int _SubscriptionId;
		
		private string _IssueDescription;
		
		private System.DateTime _DateFrom;
		
		private System.DateTime _EndDate;
		
		private System.Nullable<decimal> _Value;
		
		public MIMS_SubscriptionDoc_SubscriptionIssue_ReverseablesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueId", DbType="Int NOT NULL")]
		public int IssueId
		{
			get
			{
				return this._IssueId;
			}
			set
			{
				if ((this._IssueId != value))
				{
					this._IssueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="Int NOT NULL")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IssueDescription
		{
			get
			{
				return this._IssueDescription;
			}
			set
			{
				if ((this._IssueDescription != value))
				{
					this._IssueDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFrom", DbType="DateTime NOT NULL")]
		public System.DateTime DateFrom
		{
			get
			{
				return this._DateFrom;
			}
			set
			{
				if ((this._DateFrom != value))
				{
					this._DateFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Decimal(23,6)")]
		public System.Nullable<decimal> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
	}
	
	public partial class MIMS_SubscriptionData_NextIssueResult
	{
		
		private int _Column1;
		
		public MIMS_SubscriptionData_NextIssueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_SubscriptionBiz_AuthorizeResult
	{
		
		private System.Nullable<int> _Seats;
		
		private string _Reason;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		public MIMS_SubscriptionBiz_AuthorizeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seats", DbType="Int")]
		public System.Nullable<int> Seats
		{
			get
			{
				return this._Seats;
			}
			set
			{
				if ((this._Seats != value))
				{
					this._Seats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(50)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this._Reason = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this._ExpirationDate = value;
				}
			}
		}
	}
	
	public partial class MIMS_SubscriptionBiz_SetInitialValuesResult
	{
		
		private System.Nullable<int> _PayerCountry;
		
		private System.Nullable<decimal> _Weight;
		
		private System.Nullable<int> _NumberOfIssues;
		
		private System.Nullable<int> _DeliveryMethod;
		
		private System.Nullable<decimal> _BaseRate;
		
		private System.Nullable<decimal> _VatRate;
		
		private System.Nullable<int> _StartIssue;
		
		private System.Nullable<int> _StartSequence;
		
		private System.Nullable<int> _LastIssue;
		
		private System.Nullable<int> _LastSequence;
		
		private System.Nullable<int> _DeliveryAddressId;
		
		public MIMS_SubscriptionBiz_SetInitialValuesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerCountry", DbType="Int")]
		public System.Nullable<int> PayerCountry
		{
			get
			{
				return this._PayerCountry;
			}
			set
			{
				if ((this._PayerCountry != value))
				{
					this._PayerCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfIssues", DbType="Int")]
		public System.Nullable<int> NumberOfIssues
		{
			get
			{
				return this._NumberOfIssues;
			}
			set
			{
				if ((this._NumberOfIssues != value))
				{
					this._NumberOfIssues = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryMethod", DbType="Int")]
		public System.Nullable<int> DeliveryMethod
		{
			get
			{
				return this._DeliveryMethod;
			}
			set
			{
				if ((this._DeliveryMethod != value))
				{
					this._DeliveryMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseRate", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> BaseRate
		{
			get
			{
				return this._BaseRate;
			}
			set
			{
				if ((this._BaseRate != value))
				{
					this._BaseRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatRate", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> VatRate
		{
			get
			{
				return this._VatRate;
			}
			set
			{
				if ((this._VatRate != value))
				{
					this._VatRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartIssue", DbType="Int")]
		public System.Nullable<int> StartIssue
		{
			get
			{
				return this._StartIssue;
			}
			set
			{
				if ((this._StartIssue != value))
				{
					this._StartIssue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartSequence", DbType="Int")]
		public System.Nullable<int> StartSequence
		{
			get
			{
				return this._StartSequence;
			}
			set
			{
				if ((this._StartSequence != value))
				{
					this._StartSequence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIssue", DbType="Int")]
		public System.Nullable<int> LastIssue
		{
			get
			{
				return this._LastIssue;
			}
			set
			{
				if ((this._LastIssue != value))
				{
					this._LastIssue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSequence", DbType="Int")]
		public System.Nullable<int> LastSequence
		{
			get
			{
				return this._LastSequence;
			}
			set
			{
				if ((this._LastSequence != value))
				{
					this._LastSequence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryAddressId", DbType="Int")]
		public System.Nullable<int> DeliveryAddressId
		{
			get
			{
				return this._DeliveryAddressId;
			}
			set
			{
				if ((this._DeliveryAddressId != value))
				{
					this._DeliveryAddressId = value;
				}
			}
		}
	}
	
	public partial class MIMS_PaymentData_DuplicateSBRowResult
	{
		
		private System.Nullable<int> _Column1;
		
		public MIMS_PaymentData_DuplicateSBRowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_LedgerData_ReversePaymentCheckResult
	{
		
		private System.Nullable<int> _Column1;
		
		public MIMS_LedgerData_ReversePaymentCheckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_IssueBiz_GetIssueIdResult
	{
		
		private int _Column1;
		
		public MIMS_IssueBiz_GetIssueIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_IssueBiz_GetSequenceNumberResult
	{
		
		private int _Column1;
		
		public MIMS_IssueBiz_GetSequenceNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_InvoiceData_ActiveSubscriptionsBeforeResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public MIMS_InvoiceData_ActiveSubscriptionsBeforeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_DeliveryDataStatic_DeliverableElectronicResult
	{
		
		private int _PayerId;
		
		private System.Nullable<decimal> _Liability;
		
		private int _SubscriptionId;
		
		private int _IssueId;
		
		private decimal _UnitPrice;
		
		private int _UnitsPerIssue;
		
		public MIMS_DeliveryDataStatic_DeliverableElectronicResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerId", DbType="Int NOT NULL")]
		public int PayerId
		{
			get
			{
				return this._PayerId;
			}
			set
			{
				if ((this._PayerId != value))
				{
					this._PayerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liability", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Liability
		{
			get
			{
				return this._Liability;
			}
			set
			{
				if ((this._Liability != value))
				{
					this._Liability = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="Int NOT NULL")]
		public int SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this._SubscriptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueId", DbType="Int NOT NULL")]
		public int IssueId
		{
			get
			{
				return this._IssueId;
			}
			set
			{
				if ((this._IssueId != value))
				{
					this._IssueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Decimal(12,6) NOT NULL")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsPerIssue", DbType="Int NOT NULL")]
		public int UnitsPerIssue
		{
			get
			{
				return this._UnitsPerIssue;
			}
			set
			{
				if ((this._UnitsPerIssue != value))
				{
					this._UnitsPerIssue = value;
				}
			}
		}
	}
	
	public partial class MIMS_DeliveryAddressDoc_DeliveryAddress_NonStandardResult
	{
		
		private int _DeliveryAddressId;
		
		public MIMS_DeliveryAddressDoc_DeliveryAddress_NonStandardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryAddressId", DbType="Int NOT NULL")]
		public int DeliveryAddressId
		{
			get
			{
				return this._DeliveryAddressId;
			}
			set
			{
				if ((this._DeliveryAddressId != value))
				{
					this._DeliveryAddressId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
